/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsCredentials {
    /// The access key ID that identifies the temporary credentials.
    #[serde(rename = "access_key_id", skip_serializing_if = "Option::is_none")]
    pub access_key_id: Option<String>,
    /// The secret access key that can be used to sign AWS API requests.
    #[serde(rename = "secret_access_key", skip_serializing_if = "Option::is_none")]
    pub secret_access_key: Option<String>,
    /// The token that users must pass to AWS API to use the temporary credentials.
    #[serde(rename = "session_token", skip_serializing_if = "Option::is_none")]
    pub session_token: Option<String>,
}

impl AwsCredentials {
    pub fn new() -> AwsCredentials {
        AwsCredentials {
            access_key_id: None,
            secret_access_key: None,
            session_token: None,
        }
    }
}

