/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFunctionRequest {
    #[serde(rename = "function_info")]
    pub function_info: Box<models::CreateFunction>,
}

impl CreateFunctionRequest {
    pub fn new(function_info: models::CreateFunction) -> CreateFunctionRequest {
        CreateFunctionRequest {
            function_info: Box::new(function_info),
        }
    }
}

