/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFunction {
    /// Name of function, relative to parent schema.
    #[serde(rename = "name")]
    pub name: String,
    /// Name of parent catalog.
    #[serde(rename = "catalog_name")]
    pub catalog_name: String,
    /// Name of parent schema relative to its parent catalog.
    #[serde(rename = "schema_name")]
    pub schema_name: String,
    #[serde(rename = "input_params")]
    pub input_params: Box<models::FunctionParameterInfos>,
    #[serde(rename = "data_type")]
    pub data_type: models::ColumnTypeName,
    /// Pretty printed function data type.
    #[serde(rename = "full_data_type")]
    pub full_data_type: String,
    #[serde(rename = "return_params", skip_serializing_if = "Option::is_none")]
    pub return_params: Option<Box<models::FunctionParameterInfos>>,
    /// Function language. When **EXTERNAL** is used, the language of the routine function should be specified in the __external_language__ field,  and the __return_params__ of the function cannot be used (as **TABLE** return type is not supported), and the __sql_data_access__ field must be **NO_SQL**. 
    #[serde(rename = "routine_body")]
    pub routine_body: RoutineBody,
    /// Function body.
    #[serde(rename = "routine_definition")]
    pub routine_definition: String,
    #[serde(rename = "routine_dependencies", skip_serializing_if = "Option::is_none")]
    pub routine_dependencies: Option<Box<models::DependencyList>>,
    /// Function parameter style. **S** is the value for SQL.
    #[serde(rename = "parameter_style")]
    pub parameter_style: ParameterStyle,
    /// Whether the function is deterministic.
    #[serde(rename = "is_deterministic")]
    pub is_deterministic: bool,
    /// Function SQL data access.
    #[serde(rename = "sql_data_access")]
    pub sql_data_access: SqlDataAccess,
    /// Function null call.
    #[serde(rename = "is_null_call")]
    pub is_null_call: bool,
    /// Function security type.
    #[serde(rename = "security_type")]
    pub security_type: SecurityType,
    /// Specific name of the function; Reserved for future use.
    #[serde(rename = "specific_name")]
    pub specific_name: String,
    /// User-provided free-form text description.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// JSON-serialized key-value pair map, encoded (escaped) as a string.
    #[serde(rename = "properties")]
    pub properties: String,
    /// External language of the function.
    #[serde(rename = "external_language", skip_serializing_if = "Option::is_none")]
    pub external_language: Option<String>,
}

impl CreateFunction {
    pub fn new(name: String, catalog_name: String, schema_name: String, input_params: models::FunctionParameterInfos, data_type: models::ColumnTypeName, full_data_type: String, routine_body: RoutineBody, routine_definition: String, parameter_style: ParameterStyle, is_deterministic: bool, sql_data_access: SqlDataAccess, is_null_call: bool, security_type: SecurityType, specific_name: String, properties: String) -> CreateFunction {
        CreateFunction {
            name,
            catalog_name,
            schema_name,
            input_params: Box::new(input_params),
            data_type,
            full_data_type,
            return_params: None,
            routine_body,
            routine_definition,
            routine_dependencies: None,
            parameter_style,
            is_deterministic,
            sql_data_access,
            is_null_call,
            security_type,
            specific_name,
            comment: None,
            properties,
            external_language: None,
        }
    }
}
/// Function language. When **EXTERNAL** is used, the language of the routine function should be specified in the __external_language__ field,  and the __return_params__ of the function cannot be used (as **TABLE** return type is not supported), and the __sql_data_access__ field must be **NO_SQL**. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoutineBody {
    #[serde(rename = "SQL")]
    Sql,
    #[serde(rename = "EXTERNAL")]
    External,
}

impl Default for RoutineBody {
    fn default() -> RoutineBody {
        Self::Sql
    }
}
/// Function parameter style. **S** is the value for SQL.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParameterStyle {
    #[serde(rename = "S")]
    S,
}

impl Default for ParameterStyle {
    fn default() -> ParameterStyle {
        Self::S
    }
}
/// Function SQL data access.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SqlDataAccess {
    #[serde(rename = "CONTAINS_SQL")]
    ContainsSql,
    #[serde(rename = "READS_SQL_DATA")]
    ReadsSqlData,
    #[serde(rename = "NO_SQL")]
    NoSql,
}

impl Default for SqlDataAccess {
    fn default() -> SqlDataAccess {
        Self::ContainsSql
    }
}
/// Function security type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityType {
    #[serde(rename = "DEFINER")]
    Definer,
}

impl Default for SecurityType {
    fn default() -> SecurityType {
        Self::Definer
    }
}

