/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSchema {
    /// Name of schema, relative to parent catalog.
    #[serde(rename = "name")]
    pub name: String,
    /// Name of parent catalog.
    #[serde(rename = "catalog_name")]
    pub catalog_name: String,
    /// User-provided free-form text description.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// A map of key-value properties attached to the securable.
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
}

impl CreateSchema {
    pub fn new(name: String, catalog_name: String) -> CreateSchema {
        CreateSchema {
            name,
            catalog_name,
            comment: None,
            properties: None,
        }
    }
}

