/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionParameterInfo {
    /// Name of parameter.
    #[serde(rename = "name")]
    pub name: String,
    /// Full data type spec, SQL/catalogString text.
    #[serde(rename = "type_text")]
    pub type_text: String,
    /// Full data type spec, JSON-serialized.
    #[serde(rename = "type_json")]
    pub type_json: String,
    #[serde(rename = "type_name")]
    pub type_name: models::ColumnTypeName,
    /// Digits of precision; required on Create for DecimalTypes.
    #[serde(rename = "type_precision", skip_serializing_if = "Option::is_none")]
    pub type_precision: Option<i32>,
    /// Digits to right of decimal; Required on Create for DecimalTypes.
    #[serde(rename = "type_scale", skip_serializing_if = "Option::is_none")]
    pub type_scale: Option<i32>,
    /// Format of IntervalType.
    #[serde(rename = "type_interval_type", skip_serializing_if = "Option::is_none")]
    pub type_interval_type: Option<String>,
    /// Ordinal position of column (starting at position 0).
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "parameter_mode", skip_serializing_if = "Option::is_none")]
    pub parameter_mode: Option<models::FunctionParameterMode>,
    #[serde(rename = "parameter_type", skip_serializing_if = "Option::is_none")]
    pub parameter_type: Option<models::FunctionParameterType>,
    /// Default value of the parameter.
    #[serde(rename = "parameter_default", skip_serializing_if = "Option::is_none")]
    pub parameter_default: Option<String>,
    /// User-provided free-form text description.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl FunctionParameterInfo {
    pub fn new(name: String, type_text: String, type_json: String, type_name: models::ColumnTypeName, position: i32) -> FunctionParameterInfo {
        FunctionParameterInfo {
            name,
            type_text,
            type_json,
            type_name,
            type_precision: None,
            type_scale: None,
            type_interval_type: None,
            position,
            parameter_mode: None,
            parameter_type: None,
            parameter_default: None,
            comment: None,
        }
    }
}

