/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionInfo {
    /// Name of function, relative to parent schema.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Name of parent catalog.
    #[serde(rename = "catalog_name", skip_serializing_if = "Option::is_none")]
    pub catalog_name: Option<String>,
    /// Name of parent schema relative to its parent catalog.
    #[serde(rename = "schema_name", skip_serializing_if = "Option::is_none")]
    pub schema_name: Option<String>,
    #[serde(rename = "input_params", skip_serializing_if = "Option::is_none")]
    pub input_params: Option<Box<models::FunctionParameterInfos>>,
    #[serde(rename = "data_type", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<models::ColumnTypeName>,
    /// Pretty printed function data type.
    #[serde(rename = "full_data_type", skip_serializing_if = "Option::is_none")]
    pub full_data_type: Option<String>,
    #[serde(rename = "return_params", skip_serializing_if = "Option::is_none")]
    pub return_params: Option<Box<models::FunctionParameterInfos>>,
    /// Function language. When **EXTERNAL** is used, the language of the routine function should be specified in the __external_language__ field,  and the __return_params__ of the function cannot be used (as **TABLE** return type is not supported), and the __sql_data_access__ field must be **NO_SQL**. 
    #[serde(rename = "routine_body", skip_serializing_if = "Option::is_none")]
    pub routine_body: Option<RoutineBody>,
    /// Function body.
    #[serde(rename = "routine_definition", skip_serializing_if = "Option::is_none")]
    pub routine_definition: Option<String>,
    #[serde(rename = "routine_dependencies", skip_serializing_if = "Option::is_none")]
    pub routine_dependencies: Option<Box<models::DependencyList>>,
    /// Function parameter style. **S** is the value for SQL.
    #[serde(rename = "parameter_style", skip_serializing_if = "Option::is_none")]
    pub parameter_style: Option<ParameterStyle>,
    /// Whether the function is deterministic.
    #[serde(rename = "is_deterministic", skip_serializing_if = "Option::is_none")]
    pub is_deterministic: Option<bool>,
    /// Function SQL data access.
    #[serde(rename = "sql_data_access", skip_serializing_if = "Option::is_none")]
    pub sql_data_access: Option<SqlDataAccess>,
    /// Function null call.
    #[serde(rename = "is_null_call", skip_serializing_if = "Option::is_none")]
    pub is_null_call: Option<bool>,
    /// Function security type.
    #[serde(rename = "security_type", skip_serializing_if = "Option::is_none")]
    pub security_type: Option<SecurityType>,
    /// Specific name of the function; Reserved for future use.
    #[serde(rename = "specific_name", skip_serializing_if = "Option::is_none")]
    pub specific_name: Option<String>,
    /// User-provided free-form text description.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// JSON-serialized key-value pair map, encoded (escaped) as a string.
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<String>,
    /// Full name of function, in form of __catalog_name__.__schema_name__.__function__name__
    #[serde(rename = "full_name", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    /// Time at which this function was created, in epoch milliseconds.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Time at which this function was last updated, in epoch milliseconds.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Id of Function, relative to parent schema.
    #[serde(rename = "function_id", skip_serializing_if = "Option::is_none")]
    pub function_id: Option<String>,
    /// External language of the function.
    #[serde(rename = "external_language", skip_serializing_if = "Option::is_none")]
    pub external_language: Option<String>,
}

impl FunctionInfo {
    pub fn new() -> FunctionInfo {
        FunctionInfo {
            name: None,
            catalog_name: None,
            schema_name: None,
            input_params: None,
            data_type: None,
            full_data_type: None,
            return_params: None,
            routine_body: None,
            routine_definition: None,
            routine_dependencies: None,
            parameter_style: None,
            is_deterministic: None,
            sql_data_access: None,
            is_null_call: None,
            security_type: None,
            specific_name: None,
            comment: None,
            properties: None,
            full_name: None,
            created_at: None,
            updated_at: None,
            function_id: None,
            external_language: None,
        }
    }
}
/// Function language. When **EXTERNAL** is used, the language of the routine function should be specified in the __external_language__ field,  and the __return_params__ of the function cannot be used (as **TABLE** return type is not supported), and the __sql_data_access__ field must be **NO_SQL**. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoutineBody {
    #[serde(rename = "SQL")]
    Sql,
    #[serde(rename = "EXTERNAL")]
    External,
}

impl Default for RoutineBody {
    fn default() -> RoutineBody {
        Self::Sql
    }
}
/// Function parameter style. **S** is the value for SQL.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParameterStyle {
    #[serde(rename = "S")]
    S,
}

impl Default for ParameterStyle {
    fn default() -> ParameterStyle {
        Self::S
    }
}
/// Function SQL data access.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SqlDataAccess {
    #[serde(rename = "CONTAINS_SQL")]
    ContainsSql,
    #[serde(rename = "READS_SQL_DATA")]
    ReadsSqlData,
    #[serde(rename = "NO_SQL")]
    NoSql,
}

impl Default for SqlDataAccess {
    fn default() -> SqlDataAccess {
        Self::ContainsSql
    }
}
/// Function security type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityType {
    #[serde(rename = "DEFINER")]
    Definer,
}

impl Default for SecurityType {
    fn default() -> SecurityType {
        Self::Definer
    }
}

