/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionParameterInfos {
    /// The array of __FunctionParameterInfo__ definitions of the function's parameters.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<models::FunctionParameterInfo>>,
}

impl FunctionParameterInfos {
    pub fn new() -> FunctionParameterInfos {
        FunctionParameterInfos {
            parameters: None,
        }
    }
}

