/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionDependency : A function that is dependent on a SQL object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionDependency {
    /// Full name of the dependent function, in the form of __catalog_name__.__schema_name__.__function_name__.
    #[serde(rename = "function_full_name")]
    pub function_full_name: String,
}

impl FunctionDependency {
    /// A function that is dependent on a SQL object.
    pub fn new(function_full_name: String) -> FunctionDependency {
        FunctionDependency {
            function_full_name,
        }
    }
}

