/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateTemporaryTableCredential {
    /// Table id for which temporary credentials are generated.  Can be obtained from tables/{full_name} (get table info) API. 
    #[serde(rename = "table_id")]
    pub table_id: String,
    #[serde(rename = "operation")]
    pub operation: models::TableOperation,
}

impl GenerateTemporaryTableCredential {
    pub fn new(table_id: String, operation: models::TableOperation) -> GenerateTemporaryTableCredential {
        GenerateTemporaryTableCredential {
            table_id,
            operation,
        }
    }
}

