/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateTemporaryVolumeCredential {
    /// Volume id for which temporary credentials are generated.  Can be obtained from volumes/{full_name} (get volume info) API. 
    #[serde(rename = "volume_id")]
    pub volume_id: String,
    #[serde(rename = "operation")]
    pub operation: models::VolumeOperation,
}

impl GenerateTemporaryVolumeCredential {
    pub fn new(volume_id: String, operation: models::VolumeOperation) -> GenerateTemporaryVolumeCredential {
        GenerateTemporaryVolumeCredential {
            volume_id,
            operation,
        }
    }
}

