/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateTemporaryTableCredentialResponse {
    #[serde(rename = "aws_temp_credentials", skip_serializing_if = "Option::is_none")]
    pub aws_temp_credentials: Option<Box<models::AwsCredentials>>,
    /// Server time when the credential will expire, in epoch milliseconds. The API client is advised to cache the credential given this expiration time. 
    #[serde(rename = "expiration_time", skip_serializing_if = "Option::is_none")]
    pub expiration_time: Option<i64>,
}

impl GenerateTemporaryTableCredentialResponse {
    pub fn new() -> GenerateTemporaryTableCredentialResponse {
        GenerateTemporaryTableCredentialResponse {
            aws_temp_credentials: None,
            expiration_time: None,
        }
    }
}

