/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TableDependency : A table that is dependent on a SQL object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableDependency {
    /// Full name of the dependent table, in the form of __catalog_name__.__schema_name__.__table_name__.
    #[serde(rename = "table_full_name")]
    pub table_full_name: String,
}

impl TableDependency {
    /// A table that is dependent on a SQL object.
    pub fn new(table_full_name: String) -> TableDependency {
        TableDependency {
            table_full_name,
        }
    }
}

