/*
 * Unity Catalog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TableType {
    #[serde(rename = "MANAGED")]
    Managed,
    #[serde(rename = "EXTERNAL")]
    External,

}

impl std::fmt::Display for TableType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Managed => write!(f, "MANAGED"),
            Self::External => write!(f, "EXTERNAL"),
        }
    }
}

impl Default for TableType {
    fn default() -> TableType {
        Self::Managed
    }
}

